### ISSUE TITLE
Return to previous intent instead of showing errors

### ISSUE THREAD

**Issue by fr33z3** [developermypos/myPOS-Glass-SDK#1]
Hello, I'm trying to integrate myPOS glass with my own application. Is there a way that on cancelled of failed transaction glass finished it's own intent and returned to MainActivity instead of showing me the error screen?

**Comment by StiliyanKovachev** [comment]
Hello,

There is no way to skip the transaction failure screen. The application is required to show the customer what is the transaction result.

**Comment by fr33z3** [comment]
@StiliyanKovachev what is the point of integration then? I mean my own application can show it properly.

**Comment by StiliyanKovachev** [comment]
Hi @fr33z3 ,

after internal discussion with the team, from the next version of myPOS Glass app, when you pass skipConfirmationScreen = true , the transaction cancel screen will self finish after 3 seconds on display.

If you want a demo version of the application contact us via email: online@mypos.com

**Comment by hussain-kooky2go** [comment]
Hi @StiliyanKovachev ,
Thanks for accommodating this change in the myPOS application. 
Is there an ETA when would this feature be available in the next version of myPOS application?

**Comment by StiliyanKovachev** [comment]
Hi,

there is no changes needed in the SDK. You can find the **skipConfirmationScreen** parameter [here](https://github.com/developermypos/myPOS-Glass-SDK/blob/c8f48eab9444f0ba08a216b419edf5ab82e6f35c/myposglasssdk/src/main/java/com/mypos/glasssdk/MyPOSAPI.java#L111) . The changes will be made in the myPOS Glass application. They will be released until the end of this mount.

**Comment by hussain-kooky2go** [comment]
Hi,

Thank you for the quick response. Looking forward to have this change in the next release.

Best Regards,
Hussain Marvi

**Comment by StiliyanKovachev** [comment]
released in version 1.3.3
