### ISSUE TITLE
Customer receipt disable problem

### ISSUE THREAD

**Issue by madtatu-development** [developermypos/myPOS-Glass-SDK#2]
Hi,

May I ask your kind help ?

I am tyring to get rid of the customerreceipt screen/dialogue in our integartion (using Android Studio):

![image](https://user-images.githubusercontent.com/73760229/193144300-609dc252-0c61-4206-8d56-20cae6ed868a.png)

I had added both:

.printMerchantReceipt(MyPOSUtil.RECEIPT_OFF) 
.printCustomerReceipt(MyPOSUtil.RECEIPT_OFF)
 
BUT for some reason, the screen above is still comes up. 

May I ask if there is anything addition need to be added to get rid of this screen?

(Otherwise the integartion works like teh charm)

Many thanks for your help in advance!

**Comment by StiliyanKovachev** [comment]
Hi @madtatu-development 

You can find the skipConfirmationScreen parameter [here](https://github.com/developermypos/myPOS-Glass-SDK/blob/c8f48eab9444f0ba08a216b419edf5ab82e6f35c/myposglasssdk/src/main/java/com/mypos/glasssdk/MyPOSAPI.java#L111) . If you set it **true**, it will skip the receipt screen.

**Comment by madtatu-development** [comment]
BIG thanks!
