### ISSUE TITLE
onActivityResult always return RESULT_CANCELLED

### ISSUE THREAD

**Issue by RobbeR** [developermypos/myPOS-Glass-SDK#3]
Dear developers,

I have a problem with the SDK on my test device (Xiaomi REDMI 9) while I use the demoGlass.apk. 
I can successfully make a payment on the device from my app, it opens the Intent from the demoGlass.apk after a button click, but then immediately returns to my app when the onActivityResult handled the result and the resultCode is always 0 (RESULT_CANCELLED). 
Can you help my what I'm doing wrong?

Thank you,
Robert

**Comment by StiliyanKovachev** [comment]
Hi,

Please forward your request to online@mypos.com . myPOS dev support will proceed your issue.

Thanks
